import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  employees: [
    {
      id: 1,
      name: "Richaud Beringer",
      slug: "richaud-beringer",
      jobTitle: "General Practitioner",
      jobCategory: "Doctor",
      status: "Active",
      category: "Full-time",
      address: "6391 Elgin St. Celina, Delaware.",
      phone: "+84 678 890 000",
      email: "email@example.com",
      about:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
      experience: 15,
      year: 2010,
      rating: 3,
      educations: {
        campus: "Harvard University",
        img: "/employee/campus/harvard.jpg",
        address: "Massachusetts Hall, Cambridge, United States",
      },
      satisfaction: {
        total: 1000,
        happy: 800,
      },
      patients: {
        total: [125, 150, 250, 170, 200, 150, 200],
        lists: [
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "next",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "next",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "next",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
        ],
      },
      img: "/employee/richaud-beringer.svg",
    },
    {
      id: 2,
      name: "Jacques Lyon",
      slug: "jacques-lyon",
      jobTitle: "Driver",
      jobCategory: "Driver",
      status: "Active",
      category: "Full-time",
      address: "6391 Elgin St. Celina, Delaware.",
      phone: "+84 678 890 000",
      email: "email@example.com",
      about:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
      experience: 15,
      year: 2010,
      rating: 5,
      educations: {
        campus: "Harvard University",
        img: "/employee/campus/harvard.jpg",
        address: "Massachusetts Hall, Cambridge, United States",
      },
      satisfaction: {
        total: 1000,
        happy: 800,
      },
      patients: {
        total: [125, 150, 250, 170, 200, 150, 200],
        lists: [
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
        ],
      },
      img: "/employee/richaud-beringer.svg",
    },
    {
      id: 3,
      name: "Tristram Bernard",
      slug: "tristam-bernard",
      jobTitle: "Pathologist",
      jobCategory: "Doctor",
      status: "Active",
      category: "Full-time",
      address: "6391 Elgin St. Celina, Delaware.",
      phone: "+84 678 890 000",
      email: "email@example.com",
      about:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
      experience: 15,
      year: 2010,
      rating: 5,
      educations: {
        campus: "Harvard University",
        img: "/employee/campus/harvard.jpg",
        address: "Massachusetts Hall, Cambridge, United States",
      },
      satisfaction: {
        total: 1000,
        happy: 800,
      },
      patients: {
        total: [125, 150, 250, 170, 200, 150, 200],
        lists: [
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
        ],
      },
      img: "/employee/richaud-beringer.svg",
    },
    {
      id: 4,
      name: "Ludivine Legrand",
      slug: "ludivine-legrand",
      jobTitle: "Neurologist",
      jobCategory: "Nurse",
      status: "Active",
      category: "Full-time",
      address: "6391 Elgin St. Celina, Delaware.",
      phone: "+84 678 890 000",
      email: "email@example.com",
      about:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
      experience: 15,
      year: 2010,
      rating: 5,
      educations: {
        campus: "Harvard University",
        img: "/employee/campus/harvard.jpg",
        address: "Massachusetts Hall, Cambridge, United States",
      },
      satisfaction: {
        total: 1000,
        happy: 800,
      },
      patients: {
        total: [125, 150, 250, 170, 200, 150, 200],
        lists: [
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
        ],
      },
      img: "/employee/valerian.svg",
    },
    {
      id: 5,
      name: "Mireio Nicolas",
      slug: "mireio-nicolas",
      jobTitle: "Office staff",
      jobCategory: "Doctor",
      status: "Off",
      category: "Full-time",
      address: "6391 Elgin St. Celina, Delaware.",
      phone: "+84 678 890 000",
      email: "email@example.com",
      about:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
      experience: 15,
      year: 2010,
      rating: 5,
      educations: {
        campus: "Harvard University",
        img: "/employee/campus/harvard.jpg",
        address: "Massachusetts Hall, Cambridge, United States",
      },
      satisfaction: {
        total: 1000,
        happy: 800,
      },
      patients: {
        total: [125, 150, 250, 170, 200, 150, 200],
        lists: [
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
        ],
      },
      img: "/employee/richaud-beringer.svg",
    },
    {
      id: 6,
      name: "Valérian Bret",
      slug: "valérian-bret",
      jobTitle: "Neurologist",
      jobCategory: "Nurse",
      status: "Off",
      category: "Full-time",
      address: "6391 Elgin St. Celina, Delaware.",
      phone: "+84 678 890 000",
      email: "email@example.com",
      about:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
      experience: 15,
      year: 2010,
      rating: 5,
      educations: {
        campus: "Harvard University",
        img: "/employee/campus/harvard.jpg",
        address: "Massachusetts Hall, Cambridge, United States",
      },
      satisfaction: {
        total: 1000,
        happy: 800,
      },
      patients: {
        total: [125, 150, 250, 170, 200, 150, 200],
        lists: [
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
          {
            name: "Dianne Russell",
            id: "ID089745096C4",
            img: "/patients/dianne-russell.jpg",
            time: "week",
          },
        ],
      },
      img: "/employee/valerian.svg",
    },
  ],
  employee: {},
};

const employeeSlice = createSlice({
  name: "employee",
  initialState,
  reducers: {
    setEmployee: (state, action) => {
      const employee = state.employees.find(
        (employee) => employee.id === action.payload
      );
      state.employee = employee;
    },
  },
});

export const { setEmployee } = employeeSlice.actions;
export default employeeSlice.reducer;
